language: node_js
sudo: false
node_js: 5.1
before_script:
- node --version
- npm --version
- npm install -g grunt-cli
script:
- grunt test-travis --verbose
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then grunt saucelabs-test; fi
before_deploy:
- npm install
- grunt build
- grunt dist
deploy:
  provider: npm
  email: cerealkillerway@gmail.com
  api_key:
    secure: "u7BNp0/a6062Uaip9rkw8dooHbhle7EFSxCYxelPSibrcMG6fzS+DxQ3iIuuke6oBUuy+8rgN961nVMbFJioLEIdoG6ZSvq3E13Up7JqFaWnGJyPHOA36l5+bZREKpbgIwAqdzSESekE6M0W+kMoSsDioXF+jwFp9/Zg6oM3evzA9UecyEhr/sYsFB2CSojNjFjVy/Qy70jGY+6kTcVjaRcwKulKq/WJmfKxSYt0FDWGH3EATaUsBVeub5JILlLglFofMscSRyiDiDix/Og6KFc0e2VCCbYPRd7vC5K+o8XdNLwhqB08+l2p0+jpCoFCeqXomkZvSbvA93K0AMn1/CGBxaEGANU+4DmuKYgGeKhy1qVCdBZKJtp6YO14agcxex6BnPeDda10TGE8dQKVvRvOb3mx1Om8ReCvonbKDdrKxq5kOFGOaKV65Pko2KQHgjLy4+vIF3HUyBXczNkjIKzIYYDioIyWJJpjfPUCr4uksX24N4DEPcGTjZPs5T3BcxXaMPbDBFJ+syIj7tA2oOxCBT8aPNA8sY10QykjY6Zw+dI5e1NTSttQ0339YASGt2fFA0gxrw3VZiELw3YYmJVbU9JboHOokasrSkM6WhkZbnaI07P/qVO4DhYkzDbZqlwcnxB1bxquX5YTmn/ZbOajAaHn4xhuaRda+qVowL0="
  on:
    tags: true
    branch: develop
after_success:
- grunt coveralls:travis
